# Welcome to serverless. Read the docs
# https://serverless.com/framework/docs/

# Serverless.yml is the configuration the CLI
# uses to deploy your code to your provider of choice

# The `service` block is the name of the service
service: mailcred-get-mailprovider

plugins:
  - serverless-offline

# The `provider` block defines where your service will be deployed
provider:
  name: aws
  runtime: nodejs8.10

# The `functions` block defines what code to deploy
functions:
  getEmailProviderName:
    handler: index.getEmailProviderName
    memorySize: 1536MB
    timeout: 30
    events:
      - http:
          path: emailProvider
          method: post
          cors: true
